# Generated by Django 4.0 on 2021-12-13 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trip', '0001_initial'),
        ('trip_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripmember',
            unique_together={('member', 'trip')},
        ),
    ]
