# Generated by Django 4.0 on 2021-12-13 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='content',
            new_name='explanation',
        ),
    ]
